image: docker:git

services:
  - docker:dind

before_script:
  - apk add grep python3
  - pip3 install pip --upgrade && pip3 install tox
  - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS"

test:
  stage: test
  script:
    - tox

build:
  stage: build
  script:
    - sh detect_and_build.sh
  only:
    - master

build-dev:
  stage: build
  script:
    - TAG=dev sh detect_and_build.sh
  only:
    - branches
  except:
    - master
