cache:
  key:
    files:
      - GREEN_MASTER_COMMIT.txt
  paths:
     - GREEN_MASTER_COMMIT.txt

stages:
  - generate-build-and-test-config
  - build-and-test
  - cache-update
  - readme-update

# TODO: Usage of rules is recommended instead of only-except syntax

# Calls dynamical generation script
generate-config:
  stage: generate-build-and-test-config
  script: TAG=latest-stable sh generate_build_and_test_config.sh build-and-test-config.yml
  artifacts:
    paths:
      - build-and-test-config.yml
  only:
    - master

# Generation script dev version
generate-config-dev:
  stage: generate-build-and-test-config
  script: TAG=dev sh generate_build_and_test_config.sh build-and-test-config-dev.yml
  artifacts:
    paths:
      - build-and-test-config-dev.yml
  only:
    - branches
  except:
    - master

# Run dynamically generated pipeline
build-and-test-pipeline:
  stage: build-and-test
  trigger:
    strategy: depend
    include:
      - artifact: build-and-test-config.yml
        job: generate-config
  only:
    - master

# Run dynamically generated pipeline dev version
build-and-test-pipeline-dev:
  stage: build-and-test
  trigger:
    strategy: depend
    include:
      - artifact: build-and-test-config-dev.yml
        job: generate-config-dev
  only:
    - branches
  except:
    - master

# If building and testing was success update latest passed commit
store-latest-passed-commit-to-cache:
  stage: cache-update
  script:
    - echo "$CI_COMMIT_SHA" > GREEN_MASTER_COMMIT.txt

# Update readme on git
build-list-update:
  stage: readme-update
  only:
    - master
  before_script:
    - apk add --no-cache git grep
    - eval "$(ssh-agent -s)"
    - echo "$GIT_SSH_PRIV_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.email "cincan@cincan.io"
    - git config --global user.name "CinCan Tools bot"
  script:
    - git clone git@gitlab.com:${CI_PROJECT_PATH}.git
    - cd ${CI_PROJECT_NAME}
    - pwd
    - ls
    - sh update-tools-list.sh
    - git add README.md
    - git diff --cached --exit-code && exit 0 || git commit -m "update tools list of README.md [ci skip]"
    - echo $CI_COMMIT_REF_NAME
    - git push origin HEAD:$CI_COMMIT_REF_NAME
